FROM php:8.1-apache

RUN pecl install iconv
RUN pecl install mbstring
RUN pecl install curl
RUN pecl install openssl
RUN pecl install tokenizer
RUN pecl install xmlrpc
RUN pecl install soap
RUN pecl install ctype
RUN pecl install zip
RUN pecl install gd
RUN pecl install simplexml
RUN pecl install spl
RUN pecl install pcre
RUN pecl install dom
RUN pecl install xml
RUN pecl install intl
RUN pecl install json
RUN docker-php-ext-enable iconv 
RUN docker-php-ext-enable mbstring
RUN docker-php-ext-enable curl
RUN docker-php-ext-enable openssl
RUN docker-php-ext-enable tokenizer
RUN docker-php-ext-enable xmlrpc
RUN docker-php-ext-enable soap
RUN docker-php-ext-enable ctype
RUN docker-php-ext-enable zip
RUN docker-php-ext-enable gd
RUN docker-php-ext-enable simplexml
RUN docker-php-ext-enable spl
RUN docker-php-ext-enable pcre
RUN docker-php-ext-enable dom
RUN docker-php-ext-enable xml
RUN docker-php-ext-enable intl
RUN docker-php-ext-enable json
